### ISSUE TITLE
Missing closing bracket

### ISSUE THREAD

**Issue by upperwal** [wastewater-intelligence-network/win-web-app#12]
<img width="349" alt="Screenshot 2022-02-18 at 2 18 57 PM" src="https://user-images.githubusercontent.com/5246435/154649401-5dbd1b77-0510-4e37-8dfc-aa19d265d213.png">

**Comment by TusarHarmanGit** [comment]
Fixed

<img width="221" alt="image" src="https://user-images.githubusercontent.com/99646340/154789555-60083c40-a660-4e0b-8f26-a036470ace7f.png">
