### ISSUE TITLE
Contact US body and Footer Collapse issue 

### ISSUE THREAD

**Issue by lokeshharman** [wastewater-intelligence-network/win-web-app#23]
Contact US Section -

 body and Footer Collapse issue 

![image](https://user-images.githubusercontent.com/99008620/157395488-35471b41-5c29-4fd1-9260-e8484c9e1331.png)

**Comment by TusarHarmanGit** [comment]
Fixed

![screencapture-localhost-3000-contactus-2022-03-15-13_14_41](https://user-images.githubusercontent.com/99646340/158330078-1fdd1b19-205f-42b1-934e-750bf15a1771.png)
