### ISSUE TITLE
Add social media links in the footer

### ISSUE THREAD

**Issue by upperwal** [wastewater-intelligence-network/win-web-app#34]
Twitter: https://twitter.com/NIUA_India
LinkedIn: https://www.linkedin.com/school/national-institute-of-urban-affairs
Insta: https://www.instagram.com/iscfp_mohua/

**Comment by TusarHarmanGit** [comment]
fixed code committed 

https://github.com/wastewater-intelligence-network/win-web-app/commit/592e539d96dc9582cf078e8794bfff75c5bfb659
