### ISSUE TITLE
Cities hover color is different

### ISSUE THREAD

**Issue by upperwal** [wastewater-intelligence-network/win-web-app#49]
<img width="346" alt="Screenshot 2022-03-23 at 10 09 23 PM" src="https://user-images.githubusercontent.com/5246435/159750868-0a8b6430-38d1-489f-b13e-1384b9fea1c6.png">

**Comment by TusarHarmanGit** [comment]
fixed

https://github.com/wastewater-intelligence-network/win-web-app/pull/61/commits/410e82acf0aa58ceadd0b6342aad7561497c9374
