### ISSUE TITLE
consortium page content

### ISSUE THREAD

**Issue by upperwal** [wastewater-intelligence-network/win-web-app#5]
@lokeshharman @TusarHarmanGit 

`PAGE CONTENT STARTS`

# Structure of WIN Consortium 

To institutionalise health surveillance and to bolster the urban healthcare governance in Indian cities, the pilot deployment will entail end-to-end strategies and processes for collecting and testing wastewater samples by bringing together medical experts, private companies, researchers, scientists and other relevant resource persons/institutions working in the field of WBE through the ‘WIN Consortium’. They will come together to design strategies, standardised protocols and/or support in the deployment of relevant infrastructure to track the immediate outbreak of CoViD-19 and regularly occurring diseases that can be tracked through sewage. These members will also undertake research to develop methods and technologies related to WBE. 

In order to have an efficient and functioning Consortium, the team has come up with a simplified structure. The WIN Consortium shall have a  National Working Group which will act as an advisory body where research institutes, technical experts, knowledge partners, innovation-based organization, start-ups will be a part and City Working Group at the city level will help in operationalisation and advisory of the WIN Programme. The National Institute of Urban Affairs will be the governing body of the WIN Consortium and each city will govern the city working group and will also be members of the National Working Group. The structure becomes holistic as the city becomes the common agent to capture the experts advice from the National Working Group and be the implementer of the programme on the ground.

The figure below will give an overview of a stratified structure:

![structure](https://user-images.githubusercontent.com/5246435/154426544-978753ab-943b-4995-81db-1f0b0981d1b8.jpg)

`PAGE CONTENT ENDS`

Click on the image or download the image from the following link: https://drive.google.com/file/d/1uXDZSiJPHbkKFBIUvlYFf_26280BqcO0/view?usp=sharing

**Comment by TusarHarmanGit** [comment]
Got it
