### ISSUE TITLE
Gray BG and incorrect height and width of the logo

### ISSUE THREAD

**Issue by upperwal** [wastewater-intelligence-network/win-web-app#50]
<img width="1163" alt="Screenshot 2022-03-23 at 10 10 52 PM" src="https://user-images.githubusercontent.com/5246435/159751187-21a2b5d8-3c7e-43c3-9efa-970b2483cf7b.png">
<img width="959" alt="Screenshot 2022-03-23 at 10 11 14 PM" src="https://user-images.githubusercontent.com/5246435/159751215-7508ccf0-f497-4b82-bf4e-7d8196dd68e4.png">

**Comment by TusarHarmanGit** [comment]
Gray BG and incorrect height and width of the logo issue fixed

https://github.com/wastewater-intelligence-network/win-web-app/pull/58/commits/3c2b9813c250d56294ef91859709d6233dded6b3


![image](https://user-images.githubusercontent.com/99646340/159870632-421f0748-8b03-4cf2-8e89-ac8bf9a6dce4.png)
