### ISSUE TITLE
Align address top to Knowledge top

### ISSUE THREAD

**Issue by upperwal** [wastewater-intelligence-network/win-web-app#52]
<img width="1145" alt="Screenshot 2022-03-23 at 10 16 00 PM" src="https://user-images.githubusercontent.com/5246435/159752269-eb3ec52c-795d-4ffa-a46e-cfec50835a3d.png">

**Comment by TusarHarmanGit** [comment]
fixed

![image](https://user-images.githubusercontent.com/99646340/159868443-92054829-ffc4-4f1b-853a-46fcf4220809.png)
