### ISSUE TITLE
Tricolor should have solid color and touch the bottom of the page

### ISSUE THREAD

**Issue by upperwal** [wastewater-intelligence-network/win-web-app#53]
<img width="527" alt="Screenshot 2022-03-23 at 10 18 21 PM" src="https://user-images.githubusercontent.com/5246435/159752639-c65d6ae7-05d7-4704-8708-329b3ea5cc96.png">

**Comment by upperwal** [comment]
@TusarHarmanGit Click on the image and download the SVG

![tricolor_border](https://user-images.githubusercontent.com/5246435/159888534-6292d96d-e31a-4c04-813c-b5af9aa81772.svg)

**Comment by TusarHarmanGit** [comment]
fixed

(https://github.com/wastewater-intelligence-network/win-web-app/commit/85477748b910240b55e4e9683b4b9f9a2ddd6d35)
