### ISSUE TITLE
Add header to the login page

### ISSUE THREAD

**Issue by upperwal** [wastewater-intelligence-network/win-web-app#54]

**Comment by TusarHarmanGit** [comment]
Added header in login page

https://github.com/wastewater-intelligence-network/win-web-app/commit/350fe9d2b8be9d22965e165febcbe5670910a3e3

![image](https://user-images.githubusercontent.com/99646340/159902658-e6198d76-7c31-4a4b-8241-6a1befa5b90e.png)
