### ISSUE TITLE
Text is overlapping

### ISSUE THREAD

**Issue by upperwal** [wastewater-intelligence-network/win-web-app#72]
<img width="1401" alt="Screenshot 2022-03-28 at 10 55 56 PM" src="https://user-images.githubusercontent.com/5246435/160453638-0258910c-ccf4-4d97-ad65-346e67cb2dd0.png">

**Comment by TusarHarmanGit** [comment]
which size system this bug?

**Comment by upperwal** [comment]
Will send you the size in the morning.

**Comment by TusarHarmanGit** [comment]
fixed on more then 1440 screen size
