### ISSUE TITLE
Add team details on the about us page

### ISSUE THREAD

**Issue by upperwal** [wastewater-intelligence-network/win-web-app#75]
Name, designation and organisation: https://docs.google.com/document/d/1VY3VQ3Urz5hwWt1BT9QvKOAnpOh4yYdG/edit
Images: https://drive.google.com/drive/u/8/folders/1mNTdmhYVpMCsoZFYvKJUuVDY8Gu3KGYE (Place dummy user image if the image is not available)

**Comment by TusarHarmanGit** [comment]
which one looking good?

![image](https://user-images.githubusercontent.com/99646340/160994808-3db9aa84-0832-4c21-a685-62e2a1987551.png)


![image](https://user-images.githubusercontent.com/99646340/160995273-513d0278-803f-4699-8c51-3d8a87b7bf5f.png)

**Comment by TusarHarmanGit** [comment]
done
