### ISSUE TITLE
Sub menu not closing on mouse leave

### ISSUE THREAD

**Issue by upperwal** [wastewater-intelligence-network/win-web-app#8]
Submenu should close on mouse leave which is not happening right now.

<img width="384" alt="Screenshot 2022-02-18 at 1 34 48 PM" src="https://user-images.githubusercontent.com/5246435/154642741-a55cba0c-888f-4840-87e5-f05185bdc97e.png">

**Comment by TusarHarmanGit** [comment]
Resolved
