### ISSUE TITLE
Upload partners logo

### ISSUE THREAD

**Issue by upperwal** [wastewater-intelligence-network/win-web-app#81]
List:

1. VNSGU
2. B LAL
3. SRM IST
4. HONEYWELL
5. SMIMER
6. ICMR

**Comment by upperwal** [comment]
![vnsgu](https://user-images.githubusercontent.com/5246435/160757887-a9693244-9ccc-417a-ac04-e451941f246c.jpg)
![blal](https://user-images.githubusercontent.com/5246435/160757909-68330618-94a8-4045-9725-aa43eaefdf71.jpg)
![srm](https://user-images.githubusercontent.com/5246435/160757922-82090b5c-1870-4516-b7e4-4cd33b9a980b.jpg)
![honeywell](https://user-images.githubusercontent.com/5246435/160757932-74e10935-2820-468b-a125-c370012a8afd.jpg)
![smimer](https://user-images.githubusercontent.com/5246435/160757943-48376b62-afe1-40ee-832f-01160f2429c6.jpg)
![icmr](https://user-images.githubusercontent.com/5246435/160757951-29c7e272-ea53-444e-9b95-1ec0a7015c8c.jpg)

**Comment by TusarHarmanGit** [comment]
please make one size

**Comment by lokeshharman** [comment]
https://github.com/wastewater-intelligence-network/win-web-app/pull/87
