### ISSUE TITLE
Contact Us details

### ISSUE THREAD

**Issue by upperwal** [wastewater-intelligence-network/win-web-app#82]
Use the homepage logos

Details:

1. Name: National Institute of Urban Affairs
Address: 1st and 2nd Floor, Core 4B, India Habitat Centre, Lodhi Road, New Delhi, Delhi 110003
Email: win@niua.org
Contact: 011 24643284

3. Name: Surat Smart City Development Limited
Address: 1st Floor, South Zone Office, Surat Municipal Corporation, Opp. Satyanagar, Udhna, Surat-394210, Gujarat, India.
Email: info@suratsmartcity.com
Contact: 0261 2278429

4. Name: Surat Municipal Corporation
Address: Surat Mahanagar Seva Sadan, Gordhandas Chokhawala Marg, Muglisara, Surat - 395003, Gujarat, India.
Email: dmoh.wz@suratmunicipal.gov.in
Contact: 0261 2452937

**Comment by TusarHarmanGit** [comment]
Done
