### ISSUE TITLE
Support Decision Makers header is missing from mobile view

### ISSUE THREAD

**Issue by upperwal** [wastewater-intelligence-network/win-web-app#86]
<img width="439" alt="Screenshot 2022-03-30 at 11 03 51 AM" src="https://user-images.githubusercontent.com/5246435/160758344-f177ac76-0501-49fc-a3dc-7bcf24df726b.png">

**Comment by lokeshharman** [comment]
https://github.com/wastewater-intelligence-network/win-web-app/pull/87
